doGetGrid: False
doDownload: False
doRetile: True
key: ""
list_quad_url: 'https://api.planet.com/basemaps/v1/mosaics'
geom: data/ghana_november_quads_nicfi_mini.geojson
dates: ['2019-06_2019-11']
bbox: [-2.87993585, 10.83330598,  0.0300383 , 11.17329979]
quad_dir: data/quads
tile_dir: data/tiles
temp_dir: data/temp
tilefile_path: data/ghana_tiles_buf179_mini.geojson
dst_width: 2358
dst_height: 2358
nbands: 4
dst_crs: 'EPSG:4326'
quad_name: "<quad_dir>/<qname>_<id>.tif"
tile_name: "<tile_dir>/tile<tile_id>_<date>_buf179.tif"