***REMOVED***
***REMOVED***
key: 
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
dst_img_pt: "{tile_dir}/tile{tile_id}_{date}_buf179.tif"