# Downloader
doGetGrid: False
doDownload: False
doRetile: True
key: 
list_quad_url: 'https://api.planet.com/basemaps/v1/mosaics'
geom: data/ghana_november_quads_nicfi_mini.geojson
dates: ['2019-06_2019-11']
bbox: [-2.87993585, 10.83330598,  0.0300383 , 11.17329979]
quad_dir: data/quads
tile_dir: data/tiles
temp_dir: data/temp
tilefile_path: data/ghana_tiles_buf179_mini.geojson
dst_width: 2358
dst_height: 2358
nbands: 4
dst_crs: 'EPSG:4326'
quad_name: "<quad_dir>/<qname>_<id>.tif"
tile_name: "<tile_dir>/tile<tile_id>_<date>_buf179.tif"

AWS:
  aws_access:
  aws_region: us-east-1
  aws_secret:

# Rasterization
Rasterize_Labels:
  raster_mode: binary #three_class or binary
  dir_grids: data/ghana_grid.csv
  dir_catalog: data/catalog_rasterize_test.csv
  dir_out: data/labels_test
  col_shapefile: dir_segment
  crs_epsg: 4326
  resolution: 2.5e-5
  diam: 0.0025