doGetGrid: True
doDownload: True
doRetile: False
key: ""
list_quad_url: 'https://api.planet.com/basemaps/v1/mosaics'
geom_path: data/tiles_nicfi.geojson
catalog_path: data/tz_catalog.geojson
catalog_temp_dir : data/catalog_temp_2019_11
dates: ['2019-06_2019-11']
bbox: [29.3399975929, -11.7209380022, 40.31659, -0.95]
batch_size: 50
quad_dir: data/quads
tile_dir: data/tiles
temp_dir: data/temp
tilefile_path: data/ghana_tiles_buf179_mini.geojson
dst_width: 2358
dst_height: 2358
nbands: 4
dst_crs: 'EPSG:4326'
quad_name: "<quad_dir>/<qname>.tif"
tile_name: "<tile_dir>/tile<tile_id>_<date>_buf179.tif"
